import React, { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faStar, faArrowRight } from '@fortawesome/free-solid-svg-icons';
import GlocalLogo from './GlocalLogo';
import projectsData from '../data/projects';
import './DiscoveryHub.css';

// ── Spotlight pool ───────────────────────────────────────────────────────────
// Projects that have both a non-image embed AND at least one h2/h3 in their component.
// Generated by scanning data/projects.js + src/content/*.jsx
const SPOTLIGHT_POOL = [
  1, 6, 7, 2, 3, 4, 5, 9, 10, 11, 12, 13, 14, 29, 34, 35, 37, 40, 45, 46,
  49, 50, 51, 53, 54, 56, 57, 58, 59, 60, 64, 68, 70, 71, 72, 73, 74, 76,
  77, 78, 81, 82, 84, 85, 86, 87, 88, 89, 91, 92, 93, 94, 95, 96, 98, 99,
  101, 102, 105, 106, 109, 111, 113, 114, 115, 116, 117, 119, 122, 123, 124,
  125, 126, 128, 137, 142, 143, 144, 145, 146, 147, 152, 153, 158, 162, 166,
  167, 169, 172, 173, 174, 175, 176, 180, 186, 187, 188, 193, 199, 200, 203,
  209, 211, 213, 214, 215, 220, 235, 236, 237, 242, 246, 253, 259, 266, 267,
  270, 271, 284, 288, 293, 295, 299, 300, 313, 314, 317, 325, 386,
];

// ── Helpers ───────────────────────────────────────────────────────────────────
const cap = (s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : '');

function runCountUp(target, duration, onTick) {
  let start = null;
  const raf = (ts) => {
    if (!start) start = ts;
    const prog = Math.min((ts - start) / duration, 1);
    const eased = 1 - Math.pow(1 - prog, 3);
    onTick(Math.round(eased * target));
    if (prog < 1) requestAnimationFrame(raf);
  };
  requestAnimationFrame(raf);
}

// ── Hero ─────────────────────────────────────────────────────────────────────
function HeroSection({ isFirst }) {
  const [members,  setMembers]  = useState(0);
  const [provs,    setProvs]    = useState(0);
  const [projects, setProjects] = useState(0);

  useEffect(() => {
    const delay = isFirst ? 620 : 160;
    const id = setTimeout(() => {
      runCountUp(5400,                1600, setMembers);
      runCountUp(13,                   900, setProvs);
      runCountUp(projectsData.length, 1400, setProjects);
    }, delay);
    return () => clearTimeout(id);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // On return visits, compress all delays to near-instant
  const d = (n) => isFirst ? n : n * 0.12;

  return (
    <div className="dh-hero">
      {/* ── Centred content column ── */}
      <div className="dh-hero-body">
        <GlocalLogo isFirst={isFirst} className="dh-hero-logo" />

        <motion.h2
          className="dh-hero-sub"
          initial={{ opacity: 0, y: 14 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.52, delay: d(0.26), ease: [0.2, 0, 0, 1] }}
        >
          Civic Impact, from Coast to Coast to Coast.
        </motion.h2>

        <motion.p
          className="dh-hero-desc"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.45, delay: d(0.38), ease: [0.2, 0, 0, 1] }}
        >
          GLOCAL's <em>All You Can Volunteer</em> pathway makes civic participation
          accessible and meaningful — tracked through YouCount.ca for any Canadian
          who wants to serve their community.
        </motion.p>
      </div>

      {/* ── Stats strip ── */}
      <motion.div
        className="dh-hero-stats"
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.45, delay: d(0.44), ease: [0.2, 0, 0, 1] }}
      >
        <div className="dh-hero-hl">
          <span className="dh-hero-hl-val">{members.toLocaleString()}+</span>
          <span className="dh-hero-hl-label">Members Nationwide</span>
        </div>
        <div className="dh-hero-sep" />
        <div className="dh-hero-hl">
          <span className="dh-hero-hl-val">{provs}</span>
          <span className="dh-hero-hl-label">Provinces & Territories</span>
        </div>
        <div className="dh-hero-sep" />
        <div className="dh-hero-hl">
          <span className="dh-hero-hl-val">{projects}+</span>
          <span className="dh-hero-hl-label">Projects Showcased</span>
        </div>
      </motion.div>
    </div>
  );
}

// ── Featured card ─────────────────────────────────────────────────────────────
function FeaturedCard({ project, onSelect }) {
  return (
    <button type="button" className="dh-feat-card" onClick={() => onSelect(project)}>
      <div className="dh-feat-img-wrap">
        {project.image
          ? <img src={project.image} alt={project.title} className="dh-feat-img" />
          : <div className="dh-feat-img-empty" />
        }
        {project.type && (
          <span className="dh-feat-badge">{cap(project.type)}</span>
        )}
      </div>
      <div className="dh-feat-body">
        {project.category && <span className="dh-feat-eyebrow">{project.category}</span>}
        <h3 className="dh-feat-title">{project.title}</h3>
        {project.description && <p className="dh-feat-desc">{project.description}</p>}
        <div className="dh-feat-cta">
          View Project <span className="dh-feat-arrow">→</span>
        </div>
      </div>
    </button>
  );
}

// ── Main ─────────────────────────────────────────────────────────────────────
export default function DiscoveryHub({ onSelectProject, onNavGrid }) {
  const [isFirst] = useState(() => {
    const seen = sessionStorage.getItem('glocal_intro');
    if (!seen) { sessionStorage.setItem('glocal_intro', '1'); return true; }
    return false;
  });

  // Randomized on every mount — fresh picks each visit to the Overview page
  const [featured] = useState(() => {
    const pool = SPOTLIGHT_POOL
      .map(id => projectsData.find(p => p.id === id))
      .filter(Boolean);
    for (let i = pool.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [pool[i], pool[j]] = [pool[j], pool[i]];
    }
    return pool.slice(0, 12);
  });

  // Sections below the hero stagger in after the hero settles
  const base = isFirst ? 1.05 : 0.04;
  const fu = (d = 0) => ({
    initial: { opacity: 0, y: 14 },
    animate: { opacity: 1, y: 0 },
    transition: { duration: 0.4, delay: base + d, ease: [0.2, 0, 0, 1] },
  });

  return (
    <div className="dh-page">

      {/* ── HERO ── */}
      <HeroSection isFirst={isFirst} />

      {/* ── SPOTLIGHT ── */}
      <motion.section className="dh-spotlight" {...fu(0)}>
        <div className="dh-spotlight-head">
          <div className="dh-spotlight-eyebrow">
            <FontAwesomeIcon icon={faStar} className="dh-star-icon" />
            Spotlight
          </div>
          <h2 className="dh-spotlight-title">Featured Projects</h2>
          <p className="dh-spotlight-sub">A curated selection of GLOCAL's most impactful civic work</p>
        </div>
        <div className="dh-feat-grid">
          {featured.map((project, i) => (
            <motion.div key={project.id} {...fu(0.05 + i * 0.03)}>
              <FeaturedCard project={project} onSelect={onSelectProject} />
            </motion.div>
          ))}
        </div>
      </motion.section>

      {/* ── CTA ── */}
      <motion.div className="dh-cta" {...fu(0.25)}>
        <div className="dh-cta-text">
          <span className="dh-cta-count">{projectsData.length} projects</span>
          <span className="dh-cta-label"> from across Canada — filter by type, topic, cohort, and province</span>
        </div>
        <button type="button" className="dh-cta-btn" onClick={onNavGrid}>
          Explore the full showcase
          <FontAwesomeIcon icon={faArrowRight} className="dh-cta-arrow" />
        </button>
      </motion.div>

    </div>
  );
}
